### ISSUE TITLE
Add to default HACS repos

### ISSUE THREAD

**Issue by DavidDeSloovere** [jlweston/home-assistant-custom-components#2]
I had to add this repo manually, don't know if this is normal.

Found this page with instructions to get it integrated into the known HACS repos.
https://hacs.xyz/docs/publish/start

**Comment by jlweston** [comment]
Thanks, David. The intention is for this to become a HA integration as soon as the PR has been approved, so I won't be requesting for this to be added to the default HACS repo. It just takes a while for the initial PR for a new integration to be picked up by the core devs (I hoped it would have been done by now, since it was opened in November).

It's still possible for people to add this repo to their HACS, it just takes a couple more clicks to do so.
